### ISSUE TITLE
Running async tests after previous its done

### ISSUE THREAD

**Issue by pinguxx** [WebReflection/tressa#2]
When running async tests, im getting an output of a header then i assume i will see the results related to that test, but im getting a mixed results because of the async part, tressa starts running the next test 
before finishing the current one

locally i modified the code to have a queue and only run the next test after the current async one its done

you can probably add a better version of the following, just wanted to share, maybe this is a feature that can be added to this little nice tool

```
tressa.queue = [];

tressa.run = function (fn, timer, resolve) {
    tressa.running = true;
    setTimeout(function () {
        fn(function () {
            resolve.apply(null, arguments);
            clearTimeout(timer);
            var newfn = tressa.queue.shift();
            if (newfn) {
                tressa.run(newfn[0], newfn[1], newfn[2]);
            } else {
                tressa.running = false;
            }
        });
    });
}

tressa.async = function (fn, timeout) {
    var returnObj,
        resolve = Object,
        reject = Object,
        timer = setTimeout(
            function () {
                var reason = '*timeout* ' + (fn.name || fn);
                reject(reason);
                tressa(false, reason);
            },
            timeout || tressa.timeout
        );

    returnObj = typeof Promise !== 'undefined' ?
        new Promise(function (res, rej) {
            resolve = res;
            reject = rej;
        }) :
        null

    tressa.queue.push([fn, timer, resolve]);

    if (!tressa.running) {
        var newfn = tressa.queue.shift();
        if (newfn) {
            tressa.run(newfn[0], newfn[1], newfn[2]);
        }
    }

    return returnObj;
};
```

**Comment by WebReflection** [comment]
Err ... tressa.async returns a Promise

**Comment by WebReflection** [comment]
Sorry for the quick reply, I was on a rush.

> tressa starts running the next test before finishing the current one

that's exactly what I call `async` 😉 

Tests and logs should be done once/while executed and tests don't necessarily need to be consecutive so this is rather a feature, not something to fix.

However, since sometimes we need to queue, tressa returns a `Promise` so you can queue whatever you want whenever you want.

```js
tressa.title('Taming Async');
Promise.resolve() // just to have a consistent pattern
.then(() => tressa.async(done =>
  setTimeout(() => {
    tressa.log('this is the **first**');
    done();
  }, 1000)
))
.then(() => tressa.async(done =>
  setTimeout(() => {
    tressa.log('this is the **second**');
    done();
  }, 750)
))
.then(() => tressa.async(done =>
  setTimeout(() => {
    tressa.log('this is the **third**');
    done();
  }, 500)
));
```

Hope this helps

**Comment by pinguxx** [comment]
man i guess it was too late for me, i was testing this in ie, so no promise love in it, i will throw a polyfill and be happy with it

Thanks for your answer and your help

**Comment by WebReflection** [comment]
try `promise-pjs` package, it's used by Google AMP Project too ;-)

**Comment by pinguxx** [comment]
i was using https://github.com/taylorhakes/promise-polyfill seemed to work fine but will try the pjs lol
