### ISSUE TITLE
ES6 Modules version

### ISSUE THREAD

**Issue by brettz9** [WebReflection/tressa#4]
Might you be open to releasing an ES6 Modules version?

**Comment by WebReflection** [comment]
only when it'll be needed. This is a NodeJS only module.

**Comment by WebReflection** [comment]
sorry for rushing out ... also this is duplicate of #3

**Comment by brettz9** [comment]
How is this a NodeJS-only module? You explicitly support the browser... Would you be open to a PR using Rollup (also for `consolemd`)?

**Comment by WebReflection** [comment]
> How is this a NodeJS-only module?

it's technically not but I use it only with nodejs 😅
